import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'app.name': 'Hamdard',
    'app.tagline': 'Saving Lives',
    'app.hero.title': 'Welcome To',
    'app.hero.subtitle': 'Your AI Medical Companion, We are with you - Every Moment',
    'app.hero.services': 'Our Services',
    'app.hero.greeting': "Hey, I am Hamdard AI - Your Medical Companion. I'm here to help you. Feel free to share your pain..!!",
    'app.language.select': 'Choose your language',
    'app.try_now': 'Try Now',
    'service.voice.title': 'Voice Triage',
    'service.voice.desc': 'Talk to our AI Assistant to get instant answer to your health queries',
    'service.prescription.title': 'Prescription Reader',
    'service.prescription.desc': 'Upload your prescription to get detailed information about it in simple words',
    'service.medicine.title': 'Medicine Information',
    'service.medicine.desc': 'Get clear and simple information about any medicine by typing or uploading its photo',
    'service.lab.title': 'Lab Analyzer',
    'service.lab.desc': 'Understand your lab reports with AI-powered insights and simple explanations',
    'service.visual.title': 'Visual Checker',
    'service.visual.desc': 'Analyze skin rashes, eye issues, or swelling with our visual symptom scanner',
    'service.therapist.title': 'Digital Therapist',
    'service.therapist.desc': 'Connect with our AI therapist for mental health support and guidance',
    'service.period.title': 'Period Tracker',
    'service.period.desc': 'Track your cycle and get personalized health tips for every phase',
    'service.jargon.title': 'Jargon Buster',
    'service.jargon.desc': 'Simplify complex medical by typing or snapping a photo of the word',
    'service.nutrition.title': 'Child Nutrition Scan',
    'service.nutrition.desc': 'Check the nutritional status of your child and get personalised diet recommendations',
    'service.emergency.title': 'Emergency Help 24*7',
    'service.emergency.desc': 'Find out nearest hospitals with vacant seats, send alerts and get instant ambulance service',
    'footer.copyright': 'Hamdard Copyright - All Rights Reserved',
    'footer.priority': 'Your Lives - Our Priority',
    'footer.love': 'Made with Love',
    'nav.dashboard': 'Dashboard',
    'nav.symptoms': 'Symptoms',
    'nav.therapist': 'AI Therapist',
    'nav.lab': 'Lab Insights',
    'nav.medicine': 'Medicine Info',
    'nav.emergency': 'Emergency',
    'nav.assistant': 'AI Health Assistant',
    'nav.period': 'Period Tracker',
    'nav.jargon': 'Jargon Buster',
    'nav.nutrition': 'Nutrition Scan',
    'therapist.header.title': 'Hamdard Therapist',
    'therapist.header.subtitle': 'AI Specialized',
    'therapist.header.desc': "Your non-judgmental space for mental wellness. I'm here to listen, reflect, and support your journey.",
    'therapist.status': 'Ready to Listen',
    'therapist.switch.voice': 'Switch to Voice',
    'therapist.switch.text': 'Switch to Text',
    'therapist.input.placeholder': 'Type your message here...',
    'therapist.privacy': 'Privacy Protected & Anonymous',
    'therapist.speak.hint': "Speak naturally, I'm listening",
    'voice.title': 'Voice Triage',
    'voice.subtitle': 'Hamdard Assistant',
    'voice.desc': 'I am hearing your voice. Please explain how you feel.',
    'prescription.title': 'Prescription Reader',
    'prescription.subtitle': 'AI Medical Scanner',
    'prescription.desc': 'Upload your prescription to decode medical instructions into simple language.',
    'lab.title': 'Lab Analyzer',
    'lab.subtitle': 'Smart Report Decoder',
    'lab.desc': 'Unlock insights from your blood tests and diagnostic reports instantly.',
    'emergency.title': 'Emergency Help',
    'emergency.subtitle': 'Life-Saving Network',
    'emergency.desc': 'Connecting you to the nearest medical resources when every second counts.',
    'jargon.title': 'Jargon Buster',
    'jargon.desc': 'Break down complex medical terms into simple, relatable language that everyone can understand.',
    'visual.title': 'Visual Checker',
    'visual.desc': 'Take a photo of a skin rash, eye issue, or swelling for an instant AI-powered analysis of potential causes.',
    'period.title': 'Period Tracker',
    'period.desc': 'Track your cycle with precision and get AI-powered health tips tailored to every phase of your journey.',
    'nutrition.title': 'Nutrition Scan',
    'nutrition.desc': 'Upload a photo of a child to check for signs of malnutrition and receive expert AI-powered guidance.',
    'medicine.title': 'Medicine Advisor',
    'medicine.subtitle': 'Smart Health Assistant',
    'medicine.desc': 'Upload a photo of any medicine to instantly understand its purpose, dosage, and safety warnings in simple language.',
    'medicine.purpose': 'Purpose',
    'medicine.dosage': 'Dosage Instructions',
    'medicine.warnings': 'Safety Warnings',
    'medicine.disclaimer': 'Always consult your doctor before taking any medicine. Do not self-medicate.',
    'common.upload': 'Upload Document',
    'common.processing': 'Processing...',
    'common.analyzing': 'Analyzing...',
    'common.summary': 'Summary',
    'common.advice': 'Advice',
  },
  hi: {
    'app.name': 'हमदर्द',
    'app.tagline': 'जीवन बचा रहे हैं',
    'app.hero.title': 'स्वागत है',
    'app.hero.subtitle': 'आपका एआई मेडिकल साथी, हम आपके साथ हैं - हर पल',
    'app.hero.services': 'हमारी सेवाएँ',
    'app.hero.greeting': 'नमस्ते, मैं हमदर्द एआई हूँ - आपका मेडिकल साथी। मैं यहाँ आपकी मदद के लिए हूँ। बेझिझक अपना दर्द साझा करें..!!',
    'app.language.select': 'अपनी भाषा चुनें',
    'app.try_now': 'अभी आज़माएं',
    'service.voice.title': 'वॉयस ट्राइएज',
    'service.voice.desc': 'अपने स्वास्थ्य संबंधी प्रश्नों के तुरंत उत्तर पाने के लिए हमारे एआई सहायक से बात करें',
    'service.prescription.title': 'प्रिस्क्रिप्शन रीडर',
    'service.prescription.desc': 'अपने प्रिस्क्रिप्शन के बारे में सरल शब्दों में विस्तृत जानकारी प्राप्त करने के लिए उसे अपलोड करें',
    'service.medicine.title': 'दवा की जानकारी',
    'service.medicine.desc': 'किसी भी दवा के बारे में टाइप करके या उसकी फोटो अपलोड करके स्पष्ट और सरल जानकारी प्राप्त करें',
    'service.lab.title': 'लैब विश्लेषक',
    'service.lab.desc': 'एआई-संचालित अंतर्दृष्टि और सरल स्पष्टीकरण के साथ अपनी लैब रिपोर्ट को समझें',
    'service.visual.title': 'विजुअल चेकर',
    'service.visual.desc': 'हमारे विजुअल लक्षण स्कैनर के साथ त्वचा पर चकत्ते, आंखों की समस्याओं या सूजन का विश्लेषण करें',
    'service.therapist.title': 'डिजिटल थेरेपिस्ट',
    'service.therapist.desc': 'मानसिक स्वास्थ्य सहायता और मार्गदर्शन के लिए हमारे एआई थेरेपिस्ट से जुड़ें',
    'service.period.title': 'पीरियड ट्रैकर',
    'service.period.desc': 'अपने चक्र को ट्रैक करें और हर चरण के लिए व्यक्तिगत स्वास्थ्य सुझाव प्राप्त करें',
    'service.jargon.title': 'मेडिकल डिक्शनरी',
    'service.jargon.desc': 'टाइप करके या शब्द की फोटो खींचकर जटिल मेडिकल शब्दों को सरल बनाएं',
    'service.nutrition.title': 'बाल पोषण स्कैन',
    'service.nutrition.desc': 'अपने बच्चे की पोषण स्थिति की जाँच करें और व्यक्तिगत आहार सिफारिशें प्राप्त करें',
    'service.emergency.title': 'आपातकालीन सहायता 24*7',
    'service.emergency.desc': 'खाली सीटों वाले निकटतम अस्पताल खोजें, अलर्ट भेजें और तुरंत एम्बुलेंस सेवा प्राप्त करें',
    'footer.copyright': 'हमदर्द कॉपीराइट - सर्वाधिकार सुरक्षित',
    'footer.priority': 'आपका जीवन - हमारी प्राथमिकता',
    'footer.love': 'प्यार के साथ बनाया गया',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.symptoms': 'लक्षण',
    'nav.therapist': 'एआई थेरेपिस्ट',
    'nav.lab': 'लैब इनसाइट्स',
    'nav.medicine': 'दवा जानकारी',
    'nav.emergency': 'आपातकालीन',
    'nav.assistant': 'एआई स्वास्थ्य सहायक',
    'nav.period': 'पीरियड ट्रैकर',
    'nav.jargon': 'मेडिकल डिक्शनरी',
    'nav.nutrition': 'पोषण स्कैन',
    'therapist.header.title': 'हमदर्द थेरेपिस्ट',
    'therapist.header.subtitle': 'एआई विशेषज्ञ',
    'therapist.header.desc': "मानसिक स्वास्थ्य के लिए आपका गैर-निर्णयात्मक स्थान। मैं यहाँ सुनने, विचार करने और आपकी यात्रा का समर्थन करने के लिए हूँ।",
    'therapist.status': 'सुनने के लिए तैयार',
    'therapist.switch.voice': 'वॉयस मोड',
    'therapist.switch.text': 'टेक्स्ट मोड',
    'therapist.input.placeholder': 'अपना संदेश यहाँ टाइप करें...',
    'therapist.privacy': 'गोपनीयता सुरक्षित और गुमनाम',
    'therapist.speak.hint': "स्वाभाविक रूप से बोलें, मैं सुन रहा हूँ",
    'voice.title': 'वॉयस ट्राइएज',
    'voice.subtitle': 'हमदर्द सहायक',
    'voice.desc': 'मैं आपकी आवाज़ सुन रहा हूँ। कृपया बताएं कि आप कैसा महसूस कर रहे हैं।',
    'prescription.title': 'प्रिस्क्रिप्शन रीडर',
    'prescription.subtitle': 'एआई मेडिकल स्कैनर',
    'prescription.desc': 'मेडिकल निर्देशों को सरल भाषा में समझने के लिए अपना प्रिस्क्रिप्शन अपलोड करें।',
    'lab.title': 'लैब विश्लेषक',
    'lab.subtitle': 'स्मार्ट रिपोर्ट डिकोडर',
    'lab.desc': 'अपने रक्त परीक्षणों और नैदानिक रिपोर्टों से तुरंत जानकारी प्राप्त करें।',
    'emergency.title': 'आपातकालीन सहायता',
    'emergency.subtitle': 'जीवन रक्षक नेटवर्क',
    'emergency.desc': 'जब हर सेकंड मायने रखता है, तो आपको निकटतम चिकित्सा संसाधनों से जोड़ना।',
    'jargon.title': 'मेडिकल डिक्शनरी',
    'jargon.desc': 'जटिल मेडिकल शब्दों को सरल, समझने योग्य भाषा में तोड़ें जिसे हर कोई समझ सके।',
    'visual.title': 'विजुअल चेकर',
    'visual.desc': 'संभावित कारणों के त्वरित एआई-संचालित विश्लेषण के लिए त्वचा पर लाल चकत्ते, आंखों की समस्या या सूजन की फोटो लें।',
    'period.title': 'पीरियड ट्रैकर',
    'period.desc': 'सटीकता के साथ अपने चक्र को ट्रैक करें और अपनी यात्रा के हर चरण के लिए विशिष्ट एआई-संचालित स्वास्थ्य सुझाव प्राप्त करें।',
    'nutrition.title': 'पोषण स्कैन',
    'nutrition.desc': 'कुपोषण के संकेतों की जांच के लिए बच्चे की फोटो अपलोड करें और विशेषज्ञ एआई-संचालित मार्गदर्शन प्राप्त करें।',
    'medicine.title': 'दवा सलाहकार',
    'medicine.subtitle': 'स्मार्ट स्वास्थ्य सहायक',
    'medicine.desc': 'किसी भी दवा के उद्देश्य, खुराक और सुरक्षा चेतावनियों को सरल भाषा में समझने के लिए उसकी फोटो अपलोड करें।',
    'medicine.purpose': 'उद्देश्य',
    'medicine.dosage': 'खुराक के निर्देश',
    'medicine.warnings': 'सुरक्षा चेतावनी',
    'medicine.disclaimer': 'कोई भी दवा लेने से पहले हमेशा अपने डॉक्टर से सलाह लें। खुद से दवा न लें।',
    'common.upload': 'दस्तावेज़ अपलोड करें',
    'common.processing': 'प्रक्रिया जारी है...',
    'common.analyzing': 'विश्लेषण किया जा रहा है...',
    'common.summary': 'सारांश',
    'common.advice': 'सलाह',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
